In [127]:
#Standart Python notebook imports

import itertools
import io
import os

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy.optimize as sopt
import scipy.stats as sstats
import seaborn as sns
import sklearn.ensemble
import sklearn.tree
from sklearn import datasets
from tqdm.auto import tqdm
from matplotlib import animation, pyplot, rc
data = pd.read_csv("data/data.csv")

In [126]:
#bag of features
#length
#
#
#

import string
characters = string.printable
MAX_LEN = 10


def flat(a):
    return np.array(a).reshape(-1)

def mmm(seq): # where mmm stands for min, mean, 
    return np.array([seq.min(), seq.mean(), seq.max()])

def to_str(seq):
    return seq.map(lambda x: str(x))



def length(seq):
    lengths = seq.map(lambda s: len(s))
    return mmm(lengths)

def character_appears(seq):
    features = []
    for character in characters:
        occurencies = seq.map(lambda s: s.count(character))
        features.append(mmm(occurencies))
    return flat(features)
        
    
def fixed_position_character_appears(seq):
    occurencies = np.zeros((len(characters)*2, MAX_LEN))
    for character in characters:
        for s in seq:
            for i, c in enumerate(s):
                if (i == MAX_LEN):
                    break
                occurencies[ord(character)][i] += (c == character)
    return flat(occurencies)

def
    
def bag_of_features(seq):
    detectors = [
        length,
        character_appears,
        fixed_position_character_appears,
    ]
    
    features = np.array([])
    for detector in detectors:
        features = np.append(detector(to_str(seq)), features)
    return features

In [125]:
data = data.fillna(" ")
bag_of_features(data['testing'])

(2303,)

In [128]:
data

,date,age,gender,country,state,boolean,boolean.1,boolean.2,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,2014-08-27 11:29:31,37,Female,United States,IL,NaN,No,Yes,Often,6-25,...,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,NaN
1,2014-08-27 11:29:37,44,M,United States,IN,NaN,No,No,Rarely,More than 1000,...,Don't know,Maybe,No,No,No,No,No,Don't know,No,NaN
2,2014-08-27 11:29:44,32,Male,Canada,NaN,NaN,No,No,Rarely,6-25,...,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No,NaN
3,2014-08-27 11:29:46,31,Male,United Kingdom,NaN,NaN,Yes,Yes,Often,26-100,...,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,NaN
4,2014-08-27 11:30:22,31,Male,United States,TX,NaN,No,No,Never,100-500,...,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,2015-09-12 11:17:21,26,male,United Kingdom,NaN,No,No,Yes,NaN,26-100,...,Somewhat easy,No,No,Some of them,Some of them,No,No,Don't know,No,NaN
1255,2015-09-26 01:07:35,32,Male,United States,IL,No,Yes,Yes,Often,26-100,...,Somewhat difficult,No,No,Some of them,Yes,No,No,Yes,No,NaN
1256,2015-11-07 12:36:58,34,male,United States,CA,No,Yes,Yes,Sometimes,More than 1000,...,Somewhat difficult,Yes,Yes,No,No,No,No,No,No,NaN
1257,2015-11-30 21:25:06,46,f,United States,NC,No,No,No,NaN,100-500,...,Don't know,Yes,No,No,No,No,No,No,No,NaN
1258,2016-02-01 23:04:31,25,Male,United States,IL,No,Yes,Yes,Sometimes,26-100,...,Don't know,Maybe,No,Some of them,No,No,No,Don't know,No,NaN